import styles from "./styles.module.css";
import type { _Props } from "./types";

export const Component: React.FC<_Props> = (props) => (
  <div className={styles.container}>
    <dialog
      ref={props.menu.ref}
      className={styles.menu}
      onClick={props.menu.closeOnBackgroundClick}
      onKeyDown={props.menu.closeOnEscapeKeyDown}
    >
      <div className={styles.menuList}>
        {[...Array(props.pages.length)].map((_, index) => (
          <button
            // biome-ignore lint/suspicious/noArrayIndexKey: page order is static and never changes
            key={index}
            type="button"
            className={styles.menuItem}
            onClick={() => props.switchPage(index)}
          >
            {index + 1}/{props.pages.length}
          </button>
        ))}
      </div>
    </dialog>
    <button
      type="button"
      className={styles.menuButton}
      onClick={props.menu.show}
    >
      <div className={styles.menuButtonText}>
        {props.page + 1}/{props.pages.length}
      </div>
    </button>
    <section className={styles.content}>
      <h2 ref={props.contentHeaderRef} className={styles.contentHeader}>
        Sunday Morning
      </h2>
      <div className={styles.contentMain}>
        {props.pages[props.page].map((content) => (
          <p key={content}>{content}</p>
        ))}
      </div>
      <div className={styles.contentFooter}>
        <p>this is a short story generated by ai.</p>
        <p>you can switch pages using the buttons below.</p>
      </div>
    </section>
  </div>
);
